// <auto-generated />
using System;
using ConsoleEFDescriminator.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleEFDescriminator.Migrations
{
    [DbContext(typeof(ImmobileContext))]
    partial class ImmobileContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConsoleEFDescriminator.Models.Immobile", b =>
                {
                    b.Property<Guid>("ImmobileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imovel_descriminator_tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImmobileId");

                    b.ToTable("Immobiles");

                    b.HasDiscriminator<string>("imovel_descriminator_tipo").HasValue("Immobile");
                });

            modelBuilder.Entity("ConsoleEFDescriminator.Models.Commercial", b =>
                {
                    b.HasBaseType("ConsoleEFDescriminator.Models.Immobile");

                    b.HasDiscriminator().HasValue("comercial");
                });

            modelBuilder.Entity("ConsoleEFDescriminator.Models.Residential", b =>
                {
                    b.HasBaseType("ConsoleEFDescriminator.Models.Immobile");

                    b.HasDiscriminator().HasValue("residencial");
                });
#pragma warning restore 612, 618
        }
    }
}
